### PR TITLE
Update to latest gnu config.guess and config.sub to support additional architectures

### PR DESCRIPTION
**Pull request by bernstei**
Get new config.guess and config.sub from
    https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
    https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
as per instructions in
    https://www.gnu.org/software/gettext/manual/html_node/config_002eguess.html

I think this will address #68

Works locally for me, but let's see what it does in the github CI - I'm not sure what architectures are automatically tested.

### CODE REVIEW

**Comment by bernstei** [comment]
@andreww looks like the CI is happy with the new config.guess and config.sub.  Do you want anything else before merging?

**Comment by bernstei** [comment]
Hi @andreww have you had a chance to look at this final part of the autoconfig update?

**Comment by andreww** [comment]
Afraid I've not had a chance yet. I may get a bit of time towards the end of today. If not it'll be Thursday.

**Comment by bernstei** [comment]
No problem - just wanted to make sure this didn't fall off the queue

**Comment by andreww** [comment]
Looks good to me (works locally, the tests all pass on travis) but I guess it's really a question of testing this on a machine with a new architecture. Anyway, merging (we can always roll back if this turns up a big problem elsewhere). Thanks @bernstei!

**Pull request merged**
