### PR TITLE
Arm config

### PR DESCRIPTION
**Pull request by pietrodelugas**

### CODE REVIEW

**Comment by andreww** [comment]
Sorry about the enormous delay in getting to this. I've now (finally) found a bit of time and want to merge the outstanding pull requests in order to get a new version out before the summer. 

For this one, would you mind updating the patch so old machines that report as `arm` will still be detected as well as the new `aarch64`? I think the file ought have both clauses - something like:

    arm*:Linux:*:*)
        echo ${UNAME_MACHINE}-unknown-linux-gnu
        exit ;;
    aarch64:Linux:*:*)
        echo ${UNAME_MACHINE}-unknown-linux-gnu
        exit ;;

While you are at it, could you rebase this branch so it does not include the 'colon' patch, and the revert of the colon patch?

**Comment by pietrodelugas** [comment]
ok I will add the changes and rebase. thanks a lot. Pietro

**Comment by pietrodelugas** [comment]
Rebased and modified as you suggested. I moved the base branch of the pull request from testing to master. Is it right ?

**Comment by andreww** [comment]
I've generated a new pull request (#53) to merge the commits into my master branch. I'll merge that once the travis tests have run. I'll close this one so we don't get mixed up (or double merge that change from Tom Daff).

**Pull request closed without merging**
