### PR TITLE
Some minor changes in CMake compilation system:

### PR DESCRIPTION
**Pull request by victorsndvg**
- Allows to select which targets will compile
    - Manage include_directories from the main CMakeLists.txt
    - Library names depend on project name

### CODE REVIEW

**Comment by andreww** [comment]
Any chance you could outline how these features can be used - so this information can be included in the documentation? How would a user select different project names or use different parts of FoX with cmake?

**Comment by victorsndvg** [comment]
Hello @andreww ,

I create 5 options in order to enable/disable the compilation of each high-level library and the examples:
* FoX_ENABLE_WXML
* FoX_ENABLE_WCML
* FoX_ENABLE_WKML
* FoX_ENABLE_DOM
* FoX_ENABLE_EXAMPLES

This options are enabled by default.

For example, to do a out-of-source build disabling WCML, WKML and examples with the CMake command line interface, you have to write:

```cmake -DFoX_ENABLE_WCML=OFF -DFoX_ENABLE_WKML=OFF -DFoX_ENABLE_EXAMPLES=OFF $SOURCE_DIR```

Using ```cmake-gui``` this options will be shown on the CMake window.

**Comment by victorsndvg** [comment]
About the project name:

When you create a project in CMake you use:

```PROJECT(FoX Fortran)```

The string "FoX" will be automatically stored in the PROJECT_NAME CMake variable.

I used this variable in order to name the libraries (libFoX_dom.a, libFoX_wxml.a, etc.). Now, if you change the name of the project to ```PROJECT(ASD Fortran)```, the resultant libraries will be called libASD_dom.a, libASD_xwml.a, etc.

Is not an important feature, only a bit more flexible.

Finally, I want to thank you the work with FoX. I'm going to start using it in my own project and, if you want, I will be glad to collaborate with the project.

Best regards,
Víctor.

**Comment by andreww** [comment]
Thanks - tested and merged. I really should get around to cutting a new release...

**Pull request merged**
